// src/components/misc/Lottie.vue
<script>
import lottie from 'lottie-web';

export default {
  name: 'Lottie',
  props: {
    url: {
      type: String,
      required: true,
    },
  },
  data: () => ({
    anim: undefined,
    loaded: false,
  }),
  async mounted() {
    const animData = await fetch(this.url).then((r) => r.json());

    this.anim = lottie.loadAnimation({
      container: this.$refs.container,
      animationData: animData,
    });

    this.loaded = true;
  },
  beforeDestroy() {
    this.anim.destroy();
  },
};
</script>
<template>
  <div class="lottie" :class="{ loaded: loaded }" ref="container"></div>
</template>
<style lang="scss">
.lottie {
  opacity: 0;
  transition: opacity 0.5s;

  &.loaded {
    opacity: 1;
  }
}
</style>

// src/components/misc/Lottie.tsx
import React, { useEffect, useRef, useState } from 'react';
import lottie from 'lottie-web';

export type LottieProps = {
	url: string;
};

export const Lottie: React.FC<LottieProps> = ({
	url
}) => {
	const container = useRef<HTMLDivElement>(null!);
	const [loaded, setLoaded] = useState(false);

	useEffect(() => {
		fetch(url)
			.then((r) => r.json())
			.then(animData => {
				const anim = lottie.loadAnimation({
					container: container.current,
					animationData: animData,
				});

				setLoaded(true);

				return () => anim.destroy();
			})
			.catch(err => { });
	}, [url]);

	return <div className={`${loaded ? 'opacity-100' : 'opacity-0'} transition-opacity duration-1000 h-full`} ref={container}></div>;
};
