// src/pages/Simulate.tsx
import React, { useState } from 'react'
import { useParams } from 'react-router';
import { Input } from '../components/Input';
import { Wrapper } from '../components/misc/Wrapper';
import { ResultGraphs } from '../components/ResultGraphs';
import { ResultTable } from '../components/ResultTable';
import { leagues } from '../data/leagues';
import { getAverage } from '../helpers/average';

type Params = {
	league: string;
	contest: string;
}

export const Simulate: React.FC = () => {
	const { league: leagueId, contest: contestId } = useParams<Params>();

	const [values, setValues] = useState<Record<string, string | undefined>>({});

	const contest = leagues[leagueId].contests[contestId];

	const items = Object.fromEntries(
		Object.keys(contest.banks).map((k) => {
			const bank = contest.banks[k];
			const av = getAverage(bank, values);

			return [
				k,
				{
					name: bank.title,
					note: av,
					threshold: bank.threshold,
					admitted: av > bank.threshold,
					delta: av - bank.threshold,
				},
			];
		})
	);

	const subjects = contest.subjects;

	return <div className={`my-4`}>
		<Wrapper>
			<h3 className={`font-bold text-2xl mb-4`}>Notes</h3>
			<div className={`grid gap-4 grid-cols-2 sm:grid-cols-3 lg:grid-cols-4`}>
				{Object.keys(subjects).map(k => <Input key={k} subject={subjects[k]} value={values[k]} onChange={value => setValues({ ...values, [k]: value })} />)}
			</div>

			<h2 className={`mt-16 font-bold text-2xl`}>Les résultats</h2>
			<div className={`my-4`}>
				<ResultTable items={Object.values(items)} />
			</div>

			<ResultGraphs subjects={subjects} values={values} items={items} />
		</Wrapper>
	</div>;
};

// src/views/Simulate.vue
<script lang="ts">
import { defineComponent } from 'vue';
import { leagues } from '../data/leagues';
import { getAverage } from '../helpers/average';
import { getKeys } from '../helpers/object';
const league = 'tsi';
const contestId = 'central';
type Result = {
  name: string;
  note: number;
  threshold: number;
  delta: number;
  admitted: boolean;
};
export default defineComponent({
  data: () => ({
    values: {
			
		},
  }),
  computed: {
    userStats() {
      return {
				m1: 2,
				m2:2,
				p1:14,
				p2:5,
				sii:4,
				info: 6,
				lv1:10,
				fr:3
      };
    },
    items(): Result[] {
      const contest = leagues[league].contests[contestId];
      return getKeys(contest.banks).map((k) => {
        const bank = contest.banks[k];
        const av = getAverage(bank, this.userStats);
        return {
          name: bank.title,
          note: av,
          threshold: bank.threshold,
          admitted: av > bank.threshold,
          delta: av - bank.threshold,
        };
      });
    },
    subjects: () => {
      const bankKeys = getKeys(leagues[league].contests[contestId].banks);
      return getKeys(leagues[league].contests[contestId].banks[bankKeys[0]].factors);
    },
  },
});
</script>

<template>
  <div class="wrapper">
		<br>
    <h2>À présent, analysons les résultats !</h2>
		<input v-for="subject in subjects" :key="subject" class="label input" min="0" max="20" step="0.5" type="number" v-model="$data.values[subject]" :placeholder="'Ta note pour ' + subject" />
		

    <div class="table-wrapper my-2">
      <table class="">
        <thead>
          <tr>
            <th>Banque</th>
            <th>Note</th>
            <th>Seuil</th>
            <th>Différence</th>
            <th>Admissible</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(item, index) in items" :key="index">
            <td>{{ item.name }}</td>
            <td>{{ item.note.toLocaleString('fr', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) }}</td>
            <td>{{ item.threshold.toLocaleString('fr', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) }}</td>
            <td>{{ item.delta.toLocaleString('fr', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) }}</td>
            <td>{{ item.admitted ? 'Oui' : 'Non' }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
