// src/App.tsx
import React from 'react';
import { Link, BrowserRouter as Router, Switch, Route } from 'react-router-dom';

export const App: React.FC = () => {
  return <Router>
    <div className={`grid min-h-screen`} style={{ gridTemplateRows: 'minmax(0, auto) minmax(0, 1fr) minmax(0, auto)' }}>
      <div className="p-4 bg-green-50">
        <div>
          <Link to="/">Home</Link> | <Link to="/whatis">What is ?</Link>
        </div>
      </div>
      <div>
        <Switch>
          <Route path="/:league/:contest">
          </Route>
          <Route path="/whatis">
          </Route>
          <Route path="/">
          </Route>
        </Switch>
      </div>
      <div className="p-4 bg-green-200">Footer</div>
    </div>
  </Router>;
};

// src/App.vue
<template>
  <div id="app">
    <div class="app-header">
      <div id="nav">
        <router-link to="/">Home</router-link> |
        <router-link to="/whatis">What is ?</router-link>
      </div>
    </div>
    <div class="app-main">
      <transition name="fade" mode="out-in">
        <router-view />
      </transition>
    </div>
    <div class="app-footer">
      Footer
    </div>
  </div>
</template>

<style lang="scss">
#app {
  display: grid;
  grid-template: auto 1fr auto / minmax(0, 1fr);
  gap: 0px 0px;
  grid-template-areas:
    'header'
    'main'
    'footer';
  min-height: 100vh;

  .app-header {
    grid-area: header;
  }

  .app-main {
    grid-area: main;
  }

  .app-footer {
    grid-area: footer;
  }
}
</style>
